# The following patch enables a conversion webhook for the CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gcpclustertemplates.infrastructure.cluster.x-k8s.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        # this is "\n" used as a placeholder, otherwise it will be rejected by the apiserver for being blank,
        # but we're going to set it later using the cert-manager (or potentially a patch if not using cert-manager)
        caBundle: Cg==
        service:
          namespace: system
          name: webhook-service
          path: /convert
      conversionReviewVersions: ["v1", "v1beta1"]
