apiVersion: gceproviderconfig.k8s.io/v1alpha1
kind: GCEMachineProviderSpec
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: gcemachineproviderconfig-sample
spec:
  # Add fields here
  foo: bar
