commonLabels:
  cluster.x-k8s.io/v1beta1: v1beta1

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
- bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml

# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_gcpmachines.yaml
- patches/webhook_in_gcpclusters.yaml
- patches/webhook_in_gcpmachinetemplates.yaml
- patches/webhook_in_gcpclustertemplates.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_gcpmachines.yaml
- patches/cainjection_in_gcpclusters.yaml
- patches/cainjection_in_gcpmachinetemplates.yaml
- patches/cainjection_in_gcpclustertemplates.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
