---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.3
  name: gcpmanagedcontrolplanetemplates.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
    - cluster-api
    kind: GCPManagedControlPlaneTemplate
    listKind: GCPManagedControlPlaneTemplateList
    plural: gcpmanagedcontrolplanetemplates
    shortNames:
    - amcpt
    singular: gcpmanagedcontrolplanetemplate
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: GCPManagedControlPlaneTemplate is the Schema for the GCPManagedControlPlaneTemplates
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: GCPManagedControlPlaneTemplateSpec defines the desired state
              of GCPManagedControlPlaneTemplate.
            properties:
              template:
                description: GCPManagedControlPlaneTemplateResource describes the
                  data needed to create an GCPManagedCluster from a template.
                properties:
                  spec:
                    description: GCPManagedControlPlaneTemplateResourceSpec specifies
                      an GCP managed control plane template resource.
                    properties:
                      binaryAuthorization:
                        description: |-
                          BinaryAuthorization represents the mode of operation of Binary Authorization for the GKE cluster.
                          This feature is disabled if this field is not specified.
                        enum:
                        - disabled
                        - project_singleton_policy_enforce
                        type: string
                      clusterNetwork:
                        description: ClusterNetwork define the cluster network.
                        properties:
                          pod:
                            description: Pod defines the range of CIDRBlock list from
                              where it gets the IP address.
                            properties:
                              cidrBlock:
                                description: |-
                                  CidrBlock is where all pods in the cluster are assigned an IP address from this range. Enter a range
                                  (in CIDR notation) within a network range, a mask, or leave this field blank to use a default range.
                                  This setting is permanent.
                                type: string
                            type: object
                          privateCluster:
                            description: PrivateCluster defines the private cluster
                              spec.
                            properties:
                              controlPlaneCidrBlock:
                                description: |-
                                  ControlPlaneCidrBlock is the IP range in CIDR notation to use for the hosted master network. This range must not
                                  overlap with any other ranges in use within the cluster's network. Honored when enabled is true.
                                type: string
                              controlPlaneGlobalAccess:
                                description: ControlPlaneGlobalAccess is whenever
                                  master is accessible globally or not. Honored when
                                  enabled is true.
                                type: boolean
                              disableDefaultSNAT:
                                description: DisableDefaultSNAT disables cluster default
                                  sNAT rules. Honored when enabled is true.
                                type: boolean
                              enablePrivateEndpoint:
                                description: |-
                                  EnablePrivateEndpoint: Whether the master's internal IP
                                  address is used as the cluster endpoint.
                                type: boolean
                              enablePrivateNodes:
                                description: |-
                                  EnablePrivateNodes: Whether nodes have internal IP
                                  addresses only. If enabled, all nodes are given only RFC
                                  1918 private addresses and communicate with the master via
                                  private networking.
                                type: boolean
                            type: object
                          service:
                            description: Service defines the range of CIDRBlock list
                              from where it gets the IP address.
                            properties:
                              cidrBlock:
                                description: |-
                                  CidrBlock is where cluster services will be assigned an IP address from this IP address range. Enter a range
                                  (in CIDR notation) within a network range, a mask, or leave this field blank to use a default range.
                                  This setting is permanent.
                                type: string
                            type: object
                          useIPAliases:
                            description: |-
                              UseIPAliases is whether alias IPs will be used for pod IPs in the cluster. If false, routes will be used for
                              pod IPs in the cluster.
                            type: boolean
                        type: object
                      clusterSecurity:
                        description: ClusterSecurity defines the cluster security.
                        properties:
                          authenticatorGroupConfig:
                            description: AuthenticatorGroupConfig is RBAC security
                              group for use with Google security groups in Kubernetes
                              RBAC.
                            properties:
                              securityGroups:
                                description: SecurityGroups is the name of the security
                                  group-of-groups to be used.
                                type: string
                            required:
                            - securityGroups
                            type: object
                          workloadIdentityConfig:
                            description: |-
                              WorkloadIdentityConfig allows workloads in your GKE clusters to impersonate Identity and Access Management (IAM)
                              service accounts to access Google Cloud services
                            properties:
                              workloadPool:
                                description: |-
                                  WorkloadPool is the workload pool to attach all Kubernetes service accounts to Google Cloud services.
                                  Only relevant when enabled is true
                                type: string
                            required:
                            - workloadPool
                            type: object
                        type: object
                      enableAutopilot:
                        description: EnableAutopilot indicates whether to enable autopilot
                          for this GKE cluster.
                        type: boolean
                      enableIdentityService:
                        description: EnableIdentityService indicates whether to enable
                          Identity Service component for this GKE cluster.
                        type: boolean
                      location:
                        description: |-
                          Location represents the location (region or zone) in which the GKE cluster
                          will be created.
                        type: string
                      loggingService:
                        description: |-
                          LoggingService represents configuration of logging service feature of the GKE cluster.
                          Possible values: none, logging.googleapis.com/kubernetes (default).
                          Value is ignored when enableAutopilot = true.
                        type: string
                      machineTemplate:
                        description: |-
                          MachineTemplate contains information about how machines
                          should be shaped when creating or updating a control plane.
                          For the GCPManagedControlPlaneTemplate, this field is used
                          only to fulfill the CAPI contract.
                        type: object
                      master_authorized_networks_config:
                        description: |-
                          MasterAuthorizedNetworksConfig represents configuration options for master authorized networks feature of the GKE cluster.
                          This feature is disabled if this field is not specified.
                        properties:
                          cidr_blocks:
                            description: |-
                              cidr_blocks define up to 50 external networks that could access
                              Kubernetes master through HTTPS.
                            items:
                              description: MasterAuthorizedNetworksConfigCidrBlock
                                contains an optional name and one CIDR block.
                              properties:
                                cidr_block:
                                  description: cidr_block must be specified in CIDR
                                    notation.
                                  pattern: ^(?:[0-9]{1,3}\.){3}[0-9]{1,3}(?:\/([0-9]|[1-2][0-9]|3[0-2]))?$|^([a-fA-F0-9:]+:+)+[a-fA-F0-9]+\/[0-9]{1,3}$
                                  type: string
                                display_name:
                                  description: display_name is an field for users
                                    to identify CIDR blocks.
                                  type: string
                              type: object
                            type: array
                          gcp_public_cidrs_access_enabled:
                            description: Whether master is accessible via Google Compute
                              Engine Public IP addresses.
                            type: boolean
                        type: object
                      monitoringService:
                        description: |-
                          MonitoringService represents configuration of monitoring service feature of the GKE cluster.
                          Possible values: none, monitoring.googleapis.com/kubernetes (default).
                          Value is ignored when enableAutopilot = true.
                        type: string
                      project:
                        description: Project is the name of the project to deploy
                          the cluster to.
                        type: string
                      releaseChannel:
                        description: ReleaseChannel represents the release channel
                          of the GKE cluster.
                        enum:
                        - rapid
                        - regular
                        - stable
                        - extended
                        type: string
                    required:
                    - location
                    - project
                    type: object
                required:
                - spec
                type: object
            required:
            - template
            type: object
        type: object
    served: true
    storage: true
